# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.0
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: These modules complement the official l10n_be.
repo_name: Odoo modules for Belgium
repo_slug: l10n-belgium
repo_website: https://github.com/OCA/l10n-belgium
travis_apt_packages: []
travis_apt_sources: []

