[project]
name = "odoo-addons-oca-l10n-belgium"
version = "17.0.20250430.0"
dependencies = [
    "odoo-addon-account_statement_import_coda>=17.0dev,<17.1dev",
    "odoo-addon-companyweb_base>=17.0dev,<17.1dev",
    "odoo-addon-companyweb_payment_info>=17.0dev,<17.1dev",
    "odoo-addon-l10n_be_intrastat_product>=17.0dev,<17.1dev",
    "odoo-addon-l10n_be_mis_reports>=17.0dev,<17.1dev",
    "odoo-addon-l10n_be_partner_kbo_bce>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
