[project]
name = "odoo-addons-oca-l10n-belgium"
version = "18.0.20250915.1"
dependencies = [
    "odoo-addon-companyweb_base==18.0.*",
    "odoo-addon-companyweb_payment_info==18.0.*",
    "odoo-addon-l10n_be_mis_reports==18.0.*",
    "odoo-addon-l10n_be_mis_reports_xml==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
